### ISSUE TITLE
detailed setup

### ISSUE THREAD

**Issue by fortifieditsolutions** [toadlyBroodle/twatbot#2]
can you explain like I'm 5 how to set this up properly?

**Comment by clankwright** [comment]
I've updated the README to hopefully make the initial setups a little more straight forward.
Essentially, for each platform (e.g. reddit, twitter) you'll need to follow the relevant links/guides to register a new app in order to get login credentials. Once you have auth credentials, you'll have to create new files to store them in the main directory (praw.ini, credentials.py - respectively). The format of these files need to exactly match the examples given. Then, you'll just have to install the necessary dependencies (praw, tweepy - respectively) from a terminal. So far I've not tested the script in a CMD line environment, but think I've stomped most of the Bash bugs out.

## reddit initial setup
- install <a href="https://github.com/praw-dev/praw">praw</a> python library dependency `pip install praw`
- <a href="https://praw.readthedocs.io/en/v4.0.0/getting_started/configuration/prawini.html">update 'praw.ini'</a> with <a href="https://www.reddit.com/prefs/apps/">your reddit app credentials</a>
	- <a href="http://pythonforengineers.com/build-a-reddit-bot-part-1/">how to register a new reddit app</a>

## twitter initial setup
- install <a href="https://github.com/tweepy/tweepy">tweepy</a> dependency `pip install tweepy`
- create new 'credentials.py' file in main directory with your twitter credentials
	- <a href="https://www.digitalocean.com/community/tutorials/how-to-create-a-twitterbot-with-python-3-and-the-tweepy-library">a good guide for how to get twitter credentials</a>

Hope this helps.
